# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'bitcoin-ruby', '~> 0.0.8'
gem 'json', '~> 1.8', '>= 1.8.3'
gem 'rest-client', '~> 2.1'
